{% set name = "osmdatapy" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/chourmo/osmdatapy/archive/{{ version }}.tar.gz
  sha256: 961341f8ef3583770dfe0fc36cb113eab8347142a11a9ebdc7627066f0831aa1

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python >=3.10
    - setuptools >=64
    - wheel
    - cython
    - numpy
    - setuptools-scm >=8
    - pip
  run:
    - python >=3.10
    - pandas
    - geopandas >=1.0.0
    - shapely
    - aiohttp
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - osmdatapy
  commands:
    - pip check
  requires:
    - pip

about:
  summary: A fast and simple way to parse OSM data from pbf files into Pandas Dataframess
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - chourmo
